# -*- coding: utf-8 -*-
"""ISY503_Assessment_3_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mf1OwxKR11xq54oLsV5U4Q6eBgUDBSet

# ISY503 Assessment 3 – NLP Sentiment Analysis Project

Student Name: Justin Komala Putra, Trevor Jordan Zeleang Kau, Marcus Chung Seng Lee  
Project Type: Natural Language Processing  
Dataset: Amazon Product Reviews  
Model: Bidirectional LSTM Neural Network  
Output: Positive review or Negative review
"""

!pip install tensorflow pandas numpy scikit-learn -q

import os
import re
import tarfile
import urllib.request
import pickle
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.layers import TextVectorization

DATA_URL = "https://www.cs.jhu.edu/~mdredze/datasets/sentiment/processed_acl.tar.gz"
DATA_FILE = "processed_acl.tar.gz"
DATA_DIR = "processed_acl"
CATEGORY = "electronics"

if not os.path.exists(DATA_FILE):
    print("Downloading dataset...")
    urllib.request.urlretrieve(DATA_URL, DATA_FILE)

if not os.path.exists(DATA_DIR):
    print("Extracting dataset...")
    with tarfile.open(DATA_FILE, "r:gz") as tar:
        tar.extractall()

positive_path = os.path.join(DATA_DIR, CATEGORY, "positive.review")
negative_path = os.path.join(DATA_DIR, CATEGORY, "negative.review")

print("Positive path exists:", os.path.exists(positive_path))
print("Negative path exists:", os.path.exists(negative_path))
print("Dataset ready.")

def clean_word(word):
    return re.sub(r"[^a-zA-Z]", "", word.lower())


def parse_processed_review(line):
    words = []

    for token in line.split():
        if ":" in token:
            word, count = token.rsplit(":", 1)

            if word.startswith("#label#"):
                continue

            word = clean_word(word)

            if len(word) > 1:
                try:
                    count = int(float(count))
                except:
                    count = 1

                words.extend([word] * min(count, 3))

    return " ".join(words)


def load_reviews(category):
    positive_path = os.path.join(DATA_DIR, category, "positive.review")
    negative_path = os.path.join(DATA_DIR, category, "negative.review")

    reviews = []
    labels = []

    with open(positive_path, "r", encoding="latin-1") as file:
        for line in file:
            text = parse_processed_review(line)
            if len(text.split()) > 5:
                reviews.append(text)
                labels.append(1)

    with open(negative_path, "r", encoding="latin-1") as file:
        for line in file:
            text = parse_processed_review(line)
            if len(text.split()) > 5:
                reviews.append(text)
                labels.append(0)

    data = pd.DataFrame({
        "review": reviews,
        "label": labels
    })

    data = data.sample(frac=1, random_state=42).reset_index(drop=True)
    return data


data = load_reviews(CATEGORY)

print(data.head())
print("\nLabel Count:")
print(data["label"].value_counts())
print("\nTotal Reviews:", len(data))

X = data["review"].values
y = data["label"].values

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

print("Training:", X_train.shape)
print("Validation:", X_val.shape)
print("Testing:", X_test.shape)

MAX_WORDS = 10000

vectorizer = TextVectorization(
    max_tokens=MAX_WORDS,
    output_mode="tf_idf"
)

vectorizer.adapt(X_train)

X_train_vec = vectorizer(X_train)
X_val_vec = vectorizer(X_val)
X_test_vec = vectorizer(X_test)

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(MAX_WORDS,)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

model.compile(
    loss="binary_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

model.summary()

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True
)

history = model.fit(
    X_train_vec,
    y_train,
    validation_data=(X_val_vec, y_val),
    epochs=20,
    batch_size=32,
    callbacks=[early_stop]
)

test_loss, test_accuracy = model.evaluate(X_test_vec, y_test)

print("Test Loss:", round(test_loss, 4))
print("Test Accuracy:", round(test_accuracy * 100, 2), "%")

y_pred_prob = model.predict(X_test_vec)
y_pred = (y_pred_prob >= 0.5).astype(int)

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=["Negative review", "Positive review"]
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

def predict_sentiment(review):
    review_vector = vectorizer(np.array([review]))
    prediction_score = model.predict(review_vector, verbose=0)[0][0]

    if prediction_score >= 0.5:
        prediction_label = "Positive review"
    else:
        prediction_label = "Negative review"

    return prediction_label, prediction_score

sample_reviews = [
    "This product is excellent and works perfectly.",
    "Amazing quality and very useful.",
    "The item is easy to use and worth the money.",
    "Terrible product, completely broken and useless.",
    "Worst purchase ever, very disappointed and angry.",
    "It stopped working after one day and I regret buying it.",
    "Poor quality, waste of money and not recommended."
]

print("\n=== Model Prediction Results ===\n")

for i, review in enumerate(sample_reviews, 1):
    label, score = predict_sentiment(review)

    print(f"Example {i}")
    print("Review:", review)
    print("Predicted Sentiment:", label)
    print("Confidence Score:", round(float(score), 4))
    print("-" * 60)

test_review = "This product is really good and worth buying"

label, score = predict_sentiment(test_review)

print("Review:", test_review)
print("Sentiment:", label)
print("Confidence:", round(float(score), 4))

import pickle

model.save("sentiment_model.keras")

with open("vectorizer_data.pkl", "wb") as f:
    pickle.dump({
        "vocab": vectorizer.get_vocabulary(),
        "weights": vectorizer.get_weights()
    }, f)

print("Saved correctly")

!rm vectorizer_vocab.pkl
!rm vectorizer.pkl

!ls

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pickle
# import numpy as np
# import tensorflow as tf
# from tensorflow.keras.layers import TextVectorization
# 
# st.title("Sentiment Analysis App")
# 
# st.write("This app predicts whether a product review is positive or negative.")
# 
# st.subheader("Instructions")
# st.write("Enter at least 5 words and click Analyze.")
# 
# model = tf.keras.models.load_model("sentiment_model.keras")
# 
# with open("vectorizer_data.pkl", "rb") as f:
#     vectorizer_data = pickle.load(f)
# 
# raw_vocab = vectorizer_data["vocab"]
# 
# # remove reserved tokens and duplicates
# vocab = []
# seen = set()
# for word in raw_vocab:
#     word = str(word)
#     if word in ["", "[UNK]"]:
#         continue
#     if word not in seen:
#         vocab.append(word)
#         seen.add(word)
# 
# vectorizer = TextVectorization(
#     max_tokens=10000,
#     output_mode="multi_hot"
# )
# 
# vectorizer.set_vocabulary(vocab)
# 
# user_input = st.text_area("Enter a review:")
# 
# if st.button("Analyze Sentiment"):
#     if len(user_input.split()) < 5:
#         st.warning("Enter at least 5 words")
#     else:
#         review_vector = vectorizer(tf.constant([user_input]))
#         score = model.predict(review_vector, verbose=0)[0][0]
# 
#         st.write(f"Confidence: {round(float(score), 4)}")
# 
#         if score >= 0.5:
#             st.success("Positive review")
#         else:
#             st.error("Negative review")

!pkill -f streamlit

!streamlit run app.py &

from pyngrok import ngrok

ngrok.kill()
ngrok.set_auth_token("3DAYjeaubA2KHjnwhV9iVu3Ba2g_2hdafThNVqgCRFurBdcKD")

public_url = ngrok.connect(8501, "http")
print(public_url.public_url)